<a href="https://colab.research.google.com/github/mohdfaazkhan/Natural-language-processing-NLP---Artificial-intelligence/blob/main/NLP_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
!pip install en-core-web-sm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
!pip install en-core-web-md

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement en-core-web-md (from versions: none)
ERROR: No matching distribution found for en-core-web-md


In [8]:
import spacy

In [9]:
!python -m spacy download en_core_web_sm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.8 MB 494 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [10]:
!python -m spacy download en_core_web_md

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 33.5 MB 243 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [11]:
import sklearn

In [12]:
class Category:
    BOOKS = "BOOKS"
    CLOTHING = "CLOTHING"

In [13]:
train_x = ["i love the book","this is a great book","this fit is great","i love the shoe"]
train_y =[Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer =  CountVectorizer(binary = True, ngram_range=(1,2))
train_x_vectors = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names_out())

print(train_x_vectors.toarray())


['book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love the' 'shoe' 'the' 'the book' 'the shoe' 'this' 'this fit' 'this is']
[[1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1]
 [0 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0]]


## Building a text classification model using bag-of-words(SVM)

In [15]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [16]:
text_x = vectorizer.transform(['i love the book'])
text_2 = vectorizer.transform(['you are so hot'])
print(clf_svm.predict(text_x))
print(clf_svm.predict(text_2))

['BOOKS']
['CLOTHING']


## Word Vector-  Using Spacy(Nlp library)

In [17]:
import en_core_web_sm

In [18]:
import en_core_web_md

In [19]:
nlp = spacy.load("en_core_web_sm")

In [20]:
docs = [nlp(text) for text in train_x]
print(docs)
#print(docs[0].vector)
train_x_word_vector = [x.vector for x in docs]

[i love the book, this is a great book, this fit is great, i love the shoe]


In [21]:
clf_svm_wv= svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vector, train_y)

SVC(kernel='linear')

In [22]:
test_x = ["she has pencil"]
test_docs = [nlp(text) for text in test_x]
test_x_word_vectors = [x.vector for x in test_docs]

clf_svm_wv.predict(test_x_word_vectors)

array(['CLOTHING'], dtype='<U8')

## Doc Similarity

In [23]:
nlp = spacy.load("en_core_web_sm")

In [24]:
doc1 = nlp("I like salty fries and hamburgers.")
doc2 = nlp("Fast food tastes very good.")

print(doc1,"<->", doc2, doc1.similarity(doc2))

I like salty fries and hamburgers. <-> Fast food tastes very good. 0.27134929909014804


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  after removing the cwd from sys.path.


In [25]:
import numpy as np
doc3= nlp("The Empire State Building is in New York.")
print(doc1,"<->", doc3, doc1.similarity(doc3))

doc4 = nlp("I enjoy Oranges.")
doc5 = nlp("I enjoy apples.")
doc6 = nlp("I enjoy Burgers.")
print(doc4,"<->", doc5, doc4.similarity(doc5))
print(doc4, "<->", doc6, doc4.similarity(doc6))

I like salty fries and hamburgers. <-> The Empire State Building is in New York. 0.2755579392069581
I enjoy Oranges. <-> I enjoy apples. 0.9279582931689363
I enjoy Oranges. <-> I enjoy Burgers. 0.9429192809970591


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only

## Word Similarity

In [26]:
french_fries = doc1[2:4]
burgers = doc1[5]
print(french_fries,"<->", burgers, french_fries.similarity(burgers))

salty fries <-> hamburgers 0.40727245807647705


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Span.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  This is separate from the ipykernel package so we can avoid doing imports until


## Regular Expression(Regex)

In [27]:
import re

In [28]:
regexp = re.compile(r"^ab[^\s]*cd$")
phrases = [r"abcd","xxx","abkhancd","ab cd"]
matches = []
for phrase in phrases:
    if re.match(regexp, phrase):
        matches.append(phrase)
print(matches)

['abcd', 'abkhancd']


In [29]:
regexp1 = re.compile(r"ab[^\s]*cd")
phrases = [r"abcd","xxx","aa aabkhancd mmm","ab cd"]
matches = []
for phrase in phrases:
    if re.search(regexp1, phrase):
        matches.append(phrase)
print(matches)

['abcd', 'aa aabkhancd mmm']


In [30]:
regexp2 = re.compile(r"read|story|book|body")
phrases = ["I liked story","The car treaded up the hill","I like pizza","This hat is nice"]
matches = []
for phrase in phrases:
    if re.search(regexp2, phrase):
        matches.append(phrase)
print(matches)

['I liked story', 'The car treaded up the hill']


## Chatbot

In [31]:
chat1 ='Faaz: You ask lot of questions 9919759222, faazkhanarsh@gmail.com, 9999222233310928347'
chat2 ='Faaz: Here it is: (123)-567-8912, iamarshkhan@gmail.com'
chat3 ='Faaz: Yes, phone: 12345678912 email: kaimganj@gmail.com'
pattern = '\d{10}'
matches = re.findall(pattern,chat1)
print(matches)

['9919759222', '9999222233']


In [32]:
chat1 ='Faaz: You ask lot of questions 9919759222, faazkhanarsh@gmail.com, 9999222233310928347'
chat2 ='Faaz: Here it is: (123)-567-8912, iamarshkhan@gmail.com'
chat3 ='Faaz: Yes, phone: 12345678912 email: kaimganj@gmail.com'
pattern = '\(\d{3}\)-\d{3}-\d{4}'
matches = re.findall(pattern,chat2)
print(matches)

['(123)-567-8912']


In [33]:
chat1 ='Faaz: You ask lot of questions 9919759222, faazkhanarsh@gmail.com, 9999222233310928347'
chat2 ='Faaz: Here it is: (123)-567-8912, iamarshkhan@gmail.com'
chat3 ='Faaz: Yes, phone: 12345678912 email: kaimganj@gmail.com'
chat4='Faaz: hi! (123)-567-8912 this is my landline and this my personal 9919759227' 
pattern = '\d{10}|\(\d{3}\)-\d{3}-\d{4}'
matches = re.findall(pattern,chat4)
print(matches)

['(123)-567-8912', '9919759227']


In [34]:

chat1 ='Faaz: You ask lot of questions 9919759222, faazkhanarsh@gmail.com, 9999222233310928347'
chat2 ='Faaz: Here it is: (123)-567-8912, iamarshkhan@gmail.com'
chat3 ='Faaz: Yes, phone: 12345678912 email: kaimganj@gmail.com'
chat4='Faaz: hi! (123)-567-8912 this is my landline and this my personal 9919759227' 
pattern = '[a-z0-9A-Z_]*@[a-z0-9A-Z]*\.[a-z0-9A-Z]*'
matches = re.findall(pattern,chat1)
print(matches)

['faazkhanarsh@gmail.com']


In [35]:
matches = re.findall(pattern,chat2)
print(matches)

['iamarshkhan@gmail.com']


In [36]:
matches = re.findall(pattern,chat3)
print(matches)

['kaimganj@gmail.com']


In [37]:
chat1 ='Faaz: You ask lot of questions 9919759222, faazkhanarsh@gmail.com, 9999222233310928347'
chat2 ='Faaz: Here it is: (123)-567-8912, iamarshkhan@gmail.com'
chat3 ='Faaz: Yes, phone: 12345678912 email: kaimganj@gmail.com'
chat4='Faaz: hi! (123)-567-8912 this is my landline and this my personal 9919759227' 
pattern = '[a-z0-9A-Z_]*@[a-z0-9A-Z]*\.[a-z0-9A-Z]*|\d{10}|\(\d{3}\)-\d{3}-\d{4}'
matches = re.findall(pattern,chat1)
print(matches)

['9919759222', 'faazkhanarsh@gmail.com', '9999222233']


In [38]:
matches = re.findall(pattern,chat2)
print(matches)

['(123)-567-8912', 'iamarshkhan@gmail.com']


In [39]:

matches = re.findall(pattern,chat3)
print(matches)

['1234567891', 'kaimganj@gmail.com']


## Myntra(shopping) chatbot

In [40]:
chat1='FAAZ: Hello, I am having an issue with my order # 987654321'
chat2='FAAZ: I am have problem with the order # 123456789'
chat3='FAAZ: The quality is very bad and fit is also very bad and now I want to return my order # 967061645'
pattern = 'order[^\d]*(\d*)'
matches = re.findall(pattern,chat1)
print(matches)

['987654321']


## LEMMATIZATION / STEMMING

In [41]:
import nltk

In [42]:
nltk.download('wordnet')
nltk.download('stopword')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Error loading stopword: Package 'stopword' not found in
[nltk_data]     index
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [43]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [44]:
stemmer = PorterStemmer()

pharse = "reading the books is a good habit"
words = word_tokenize(pharse)

stemmed_words = []

for word in words:
    stemmed_words.append(stemmer.stem(word))
    
" ".join(stemmed_words)


'read the book is a good habit'

In [45]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Unzipping corpora/omw-1.4.zip.


True

In [46]:
from nltk.stem import WordNetLemmatizer

In [47]:
lemmatizer = WordNetLemmatizer()

pharse = "reading the books is a good habit,"
words = word_tokenize(pharse)

lemmatize_words = []

for word in words:
    #lemmatize_words.append(lemmatizer.lemmatize(word))
    lemmatize_words.append(lemmatizer.lemmatize(word, pos='v'))
" ".join(lemmatize_words)

'read the book be a good habit ,'

## Stopword Removal

In [48]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [49]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

phrase = "Here is an example sentence demonistrate the removel of stopword"

words = word_tokenize(phrase)

stripped_phrase=[ ]
for word in words:
    if word not in stop_words:
        stripped_phrase.append(word)

" ".join(stripped_phrase)
        
     

'Here example sentence demonistrate removel stopword'

## Various other techniques(spell correction, sentiment,& pop-tagging)

In [50]:
!python -m textblob.download_corpora
!pip install textblob

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [51]:
import nltk

In [52]:
from textblob import TextBlob

In [53]:
from textblob import TextBlob
pharse ="He is very handsom and she is vry atractiv"
tb_pharse = TextBlob(pharse)

print(tb_pharse.correct())
print(tb_pharse.tags)
print(tb_pharse.sentiment)
pharse2 = "she is a doctor"
tb_pharse2 = TextBlob(pharse2)

print(tb_pharse2.sentiment)

He is very handsome and she is very attractive
[('He', 'PRP'), ('is', 'VBZ'), ('very', 'RB'), ('handsom', 'JJ'), ('and', 'CC'), ('she', 'PRP'), ('is', 'VBZ'), ('vry', 'JJ'), ('atractiv', 'NN')]
Sentiment(polarity=0.2, subjectivity=0.3)
Sentiment(polarity=0.0, subjectivity=0.0)
